apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
spec:
  rules:  
    - http:
        paths:
          - path : /api
            pathType: Prefix # can be Prefix, Exact or ImplementationSpecific
            backend:
              service: #the service where the request is forwarded
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.backend.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  number: {{ .Values.frontend.port }}
