apiVersion: v1
kind: Service
metadata:
  labels:
    app: linktree
  name: linktree
  namespace: linktree
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 3000
  selector:
    app: linktree
  type: ClusterIP
