apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-{{ .Release.Name }}
  name: redis-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: redis-{{ .Release.Name }}
    spec:
      containers:
        - image: "{{ .Values.redis.image }}:{{ .Values.redis.tag }}"
          name: redis-{{ .Release.Name }}
          ports:
          - containerPort: 6379
