apiVersion: batch/v1
kind: Job
metadata:
  name: non-indexed 
  namespace: my-ns
spec:
  completions: 6 #number of successful pods required for completion | default=1
  parallelism: 2 #number of pods running in parallel | default=1
  backoffLimit: 3 #number of total retries before failing the job | default=6
  ttlSecondsAfterFinished: 100 #seconds after the job completion the job and pods will be deleted
  template:
    metadata:
    spec:
      containers:
      - command: # In yaml, array is equivalent to a list
        - sh
        - -c #executes the following string as a command
        - echo hello world
          #this command is equivalent to ["sh","-c","echo hello"]
        image: busybox
        name: non-indexed
      restartPolicy: Never #required field

#A job is a one-off task which runs pods until the specified amount if completed
# ttl is recommended because without it, the cluster will face performance degradation even with the garbage collection
