apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: linkding
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
