apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-frontend
  name: {{ .Release.Name }}-frontend
spec:
  ports:
  - name: "{{ .Values.frontend.port }}"
    port: {{ .Values.frontend.port }}
    protocol: TCP
    targetPort: 5173
  selector:
    app: {{ .Release.Name }}-frontend
  type: ClusterIP
