apiVersion: v1
kind: Pod
metadata:
  labels:
    run: environment
  name: environment
  namespace: my-ns
spec:
  containers:
  - image: mysql:latest
    name: environment
    env:
     - name: MYSQL_ROOT_PASSWORD  
       valueFrom:
         secretKeyRef:
            name: mysql-password
            key: password
# secret of type generic is a key value pair used for confidential information
# the values can be used as environment variables using valueFrom or envFrom fields

