apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: imagepullsecrets
  name: imagepullsecrets
  namespace: my-ns
spec:
  imagePullSecrets: 
    - name: dockerhub-cred #name of the secret
  containers:
  - image: httpd
    name: imagepullsecrets
# a secret of type docker-registry is used to give kubernetes the information of the docker registry the image is on
# the infromation consists of registry host, username, password and email
