apiVersion: v1
kind: Pod
metadata:
  labels:
    run: volume
  name: volume-pod
  namespace: my-ns
spec:
  containers:
  - image: httpd
    name: volume-pod
    volumeMounts:
      - mountPath: /secret
        name: secret-volume
  volumes:
    - name: secret-volume
      secret:
        secretName: cert
        items: #optional
            - key: cert.crt
              path: ./cert.crt #used for customizing the path of the file

# secrets of generic type can also be mounted as volumes
# the keys become separate files and the content of their files are the values
# useful for storing certificates or keys instead of using env
