apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deployment
  name: clusterip
  namespace: my-ns
spec:
  ports:
    - name: 80-80
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    #matches the label of the pods
    #makes it possible for a service to refer to pods of different deployments
    app: nginx-deployment 
  type: ClusterIP
status:
  loadBalancer: {}

# service provides internal DNS and load balancing. Without a service, we can only access pods through their cluster IP address.
