apiVersion: v1
kind: Service
metadata:
  labels:
    app: headless
  name: headless
  namespace: my-ns
spec:
  ports:
  - name: "8000"
    port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: headless
  type: ClusterIP
  clusterIP: None #used to create a headless service

  # headless service disables load balancing and returns the list of IPs of the endpoints it targets when hit
  # The client can then decide which pod to hit from the list of IPs
  
  # It is mostly used with statefulsets where the client can decide which indexed pod to hit using the pod's subdomain
  # example - mysql-0.headless will resolve to the IP of the mysql-0 pod
  
  # Headless service is important because it allows others to choose which pod they want to target.
  # example - a sidecar container choosing the first or second pod to update it's labels.

