apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-ns
  name: my-ns
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-ns
  type: LoadBalancer
status:
  loadBalancer: {}

# The Load balancer service does the same work as the cluster IP service, but additionally also provisions an external Load balancer and routes the external traffic inside. When the service is created, the external IP of the field is set to <Pending>, the cloud controller manager provisions the external Load balancer after noticing the creation of the Load balancer service and returns the external IP address to be set as the IP of the provisioned Load balancer.The Load balancer service points to the pods of the Ingress controller (Ideally), which then watch the Ingress.yaml resource to route traffic internally.
