apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodeport
  name: nodeport
  namespace: my-ns
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30000 #the port at which the service is exposed externally on every node in the cluster
  selector:
    app: nginx-deployment
  type: NodePort
