apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: mealie
  namespace: mealie
spec:
  defaultBackend: #default backend is the service where the request is forwarded when none of the rules match
    service:
      name: mealie
      port:
        number: 9000
status:
  loadBalancer: {}
#the ingress resource is watched by the ingress controller
