apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-recreate
  namespace: my-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      #matches the labels of the pods as well as ownership of the replicaset
      #makes it possible for pods of different deployments to have the same label
      app: nginx-deployment 
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deployment #label of the pods created
    spec:
      #all the containers in a pod can access each other through localhost
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80 #the port at which the image is exposed
